---
# tasks file for centos-packages
- name: install necessary packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker stable repo
  shell: yum-config-manager --add-repo {{docker.repo}}

- name: install docker
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
