---
# tasks file for nkn-check
- name: check node status
  shell: docker exec nkn nknc info -s
  register: ret

- name: show node status
  debug: msg="version={{((ret.stdout|from_json)['result']['version'])}}, syncState:{{((ret.stdout|from_json)['result']['syncState'])}}, height:{{((ret.stdout|from_json)['result']['height'])}}, relayCount:{{((ret.stdout|from_json)['result']['relayMessageCount']/10000)}}"
