---
# tasks file for nkn-check
- name: check nkn service
  shell: systemctl status nkn
  ignore_errors: yes
  register: nkn_svc

- name: show nkn service status
  when: nkn_svc.stderr
  debug: msg="{{nkn_svc.stderr}}"

- name: check node status
  shell: nknc info -s
  register: ret

- name: show node status
  debug: msg="version={{((ret.stdout|from_json)['result']['version'])}}, syncState:{{((ret.stdout|from_json)['result']['syncState'])}}, height:{{((ret.stdout|from_json)['result']['height'])}}, relayCount:{{((ret.stdout|from_json)['result']['relayMessageCount'])}}"
